config/routes.rb
Rails.application.routes.draw do
  root to: "things#index"

  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/thing.rb
# == Schema Information
#
# Table name: things
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Thing < ApplicationRecord
  validates :name, presence: true

  after_create_commit -> { broadcast_refresh_to "things" }
  after_update_commit -> { broadcast_refresh_to self }
  after_destroy_commit -> { broadcast_refresh_to self }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: %i[ show edit update destroy ]

  # GET /things or /things.json
  def index
    @things = Thing.order(:created_at)
  end

  # GET /things/1 or /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream
    end
  end

  # POST /things or /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.turbo_stream
        format.html { redirect_back fallback_location: root_url, notice: "Thing was successfully created." }
        format.json { render :show, status: :created, location: @thing }
      else
        format.turbo_stream { render "create_validation_errors" }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1 or /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.turbo_stream
        format.html { redirect_to @thing, notice: "Thing was successfully updated." }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.turbo_stream { render "update_validation_errors" }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1 or /things/1.json
  def destroy
    @thing.destroy!

    respond_to do |format|
      format.html { redirect_to things_path, status: :see_other, notice: "Thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.expect(thing: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails 8 Template" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <meta name="turbo-refresh-method" content="morph">
    <meta name="turbo-refresh-scroll" content="preserve">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      turbo-cable-stream-source {
        display: none;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_edit_form.html.erb
<div id="<%= dom_id(thing) %>" style="display: flex; justify-content: space-between; max-width: 500px; border: thin grey solid; padding: 10px" data-turbo-permanent>
  <%= render "form", thing: thing %>

  <%= turbo_stream_from thing %>
</div>

app/views/things/_form.html.erb
<%= form_with(model: thing) do |form| %>
  <% if thing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
        <% thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/things/_new_form.html.erb
<div id="<%= dom_id(Thing, :new_form) %>" style="display: flex; justify-content: space-between; max-width: 500px; border: thin grey solid; padding: 10px">
  <div data-turbo-permanent>
    <%= render "form", thing: thing %>
  </div>
</div>

app/views/things/_thing.html.erb
<div id="<%= dom_id(thing) %>" style="display: flex; justify-content: space-between; max-width: 500px; border: thin grey solid; padding: 10px">
    <%= thing.name %>

    <div>
      <%= link_to "Edit", edit_thing_path(thing), data: { turbo_stream: true } %> |

      <%= link_to "Destroy", thing, data: { turbo: true, turbo_method: "delete" } %>
    </div>

    <%= turbo_stream_from thing %>
</div>

app/views/things/create.turbo_stream.erb
<turbo-stream action="refresh"></turbo-stream>

<%= turbo_stream.replace dom_id(Thing, :new_form) do %>
  <%= render "new_form", thing: Thing.new %>
<% end %>

app/views/things/create_validation_errors.turbo_stream.erb
<%= turbo_stream.replace dom_id(Thing, :new_form) do %>
  <%= render "new_form", thing: @thing %>
<% end %>

app/views/things/edit.html.erb
<% content_for :title, "Editing thing" %>

<h1>Editing thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Show this thing", @thing %> |
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/edit.turbo_stream.erb
<%= turbo_stream.replace @thing do %>
  <%= render "edit_form", thing: @thing %>
<% end %>

app/views/things/index.html.erb
<%= turbo_stream_from "things"%>

<p style="color: green"><%= notice %></p>

<% content_for :title, "Things" %>

<h1>Things</h1>

<div id="things">
  <% @things.each do |thing| %>
    <%= render thing %>
  <% end %>
</div>

<%= render "new_form", thing: Thing.new %>

app/views/things/new.html.erb
<% content_for :title, "New thing" %>

<h1>New thing</h1>

<%= render "form", thing: @thing %>

<br>

<div>
  <%= link_to "Back to things", things_path %>
</div>

app/views/things/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thing %>

<div>
  <%= link_to "Edit this thing", edit_thing_path(@thing) %> |
  <%= link_to "Back to things", things_path %>

  <%= button_to "Destroy this thing", @thing, method: :delete %>
</div>

app/views/things/update.turbo_stream.erb
<%= turbo_stream.replace @thing %>

app/views/things/update_validation_errors.turbo_stream.erb
<%= turbo_stream.update @thing do %>
  <%= render "form", thing: @thing %>

  <%= turbo_stream_from @thing %>
<% end %>